import Head from "next/head";
import Link from "next/link";

const Layout = ({ children }) => {
  return (
    <div className="p-14">
      <Head>
        <title>Rick and Morty project app</title>
        <meta name="description" content="Generated by raul bonilla" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href="/">
        <h1 className="text-4xl text-center font-bold cursor-pointer text-green-600 mb-14">
          Rick and Morty Characters
        </h1>
      </Link>
      <div>{children}</div>
    </div>
  );
};

export default Layout;
